### PR TITLE
Check prv_obj.original_file to see if it exists locally.

### PR DESCRIPTION
**Pull request by alexmorley**
TODO:

- [ ] check prv_search directories as well...

### CODE REVIEW

**Comment by magland** [comment]
Before merging this, I need to think about the following. It's important to cache checksums of files. But right now there are various systems for doing that (mountainlab, kbucket, lari, other). Challenging to (a) keep components independent and (b) reuse code. I do think that kbclient should be a dependency of both KBucket and ML. So it would make sense to have a single method for caching checksums, and have that implemented in kbclient. I think there should be some configuration options that specify which database to use for this.

**Comment by alexmorley** [comment]
That sounds sensible. Checksum caching could even be a separate dependency from kbclient?

**Comment by magland** [comment]
yes. that's a good idea. I think I'll pull sumit out as a separate js library and ultimately it can compute checksums more efficiently. By default it can cache things in /tmp? Or can be configured to cache elsewhere. What do you think about default location for caching?

**Comment by alexmorley** [comment]
I'd be tempted to go  `~/.cache/sumit` (probably purged less often...) but `/tmp` also a reasonable choice.

**Comment by magland** [comment]
I am closing this PR as this is now implemented in a separate commit.

**Pull request closed without merging**
